using Vacanam.Core.Models;

namespace Vacanam.Core.Constants;

/// <summary>
/// Catalog of all languages supported by OpenAI Whisper speech recognition models.
/// Based on OpenAI Whisper documentation and whisper.cpp specification.
/// </summary>
public static class WhisperLanguages
{
    public static readonly WhisperLanguage Default = new("en", "English", "English");

    public static readonly IReadOnlyList<WhisperLanguage> All =
    [
        // Default & Auto-detect at top
        new("en", "English", "English"),
        new("auto", "Auto-Detect", "🌐 Automatic Detection"),

        // Comprehensive OpenAI Whisper supported languages list
        new("af", "Afrikaans", "Afrikaans"),
        new("sq", "Albanian", "Shqip"),
        new("am", "Amharic", "አማርኛ"),
        new("ar", "Arabic", "العربية"),
        new("hy", "Armenian", "Հայերեն"),
        new("as", "Assamese", "অসমীয়া"),
        new("az", "Azerbaijani", "Azərbaycan"),
        new("ba", "Bashkir", "Башҡортса"),
        new("eu", "Basque", "Euskara"),
        new("be", "Belarusian", "Беларуская"),
        new("bn", "Bengali", "বাংলা"),
        new("bs", "Bosnian", "Bosanski"),
        new("br", "Breton", "Brezhoneg"),
        new("bg", "Bulgarian", "Български"),
        new("my", "Burmese", "မြန်မာ"),
        new("yue", "Cantonese", "粵語"),
        new("ca", "Catalan", "Català"),
        new("ceb", "Cebuano", "Sinugboanon"),
        new("zh", "Chinese", "中文"),
        new("hr", "Croatian", "Hrvatski"),
        new("cs", "Czech", "Čeština"),
        new("da", "Danish", "Dansk"),
        new("nl", "Dutch", "Nederlands"),
        new("et", "Estonian", "Eesti"),
        new("fo", "Faroese", "Føroyskt"),
        new("fi", "Finnish", "Suomi"),
        new("fr", "French", "Français"),
        new("gl", "Galician", "Galego"),
        new("ka", "Georgian", "ქართული"),
        new("de", "German", "Deutsch"),
        new("el", "Greek", "Ελληνικά"),
        new("gu", "Gujarati", "ગુજરાતી"),
        new("ht", "Haitian Creole", "Kreyòl ayisyen"),
        new("ha", "Hausa", "Hausa"),
        new("haw", "Hawaiian", "ʻŌlelo Hawaiʻi"),
        new("he", "Hebrew", "עברית"),
        new("hi", "Hindi", "हिन्दी"),
        new("hu", "Hungarian", "Magyar"),
        new("is", "Icelandic", "Íslenska"),
        new("id", "Indonesian", "Bahasa Indonesia"),
        new("it", "Italian", "Italiano"),
        new("ja", "Japanese", "日本語"),
        new("jw", "Javanese", "Basa Jawa"),
        new("kn", "Kannada", "ಕನ್ನಡ"),
        new("kk", "Kazakh", "Қазақша"),
        new("km", "Khmer", "ភាសាខ្មែរ"),
        new("ko", "Korean", "한국어"),
        new("lo", "Lao", "ລາວ"),
        new("la", "Latin", "Latina"),
        new("lv", "Latvian", "Latviešu"),
        new("ln", "Lingala", "Lingála"),
        new("lt", "Lithuanian", "Lietuvių"),
        new("lb", "Luxembourgish", "Lëtzebuergesch"),
        new("mk", "Macedonian", "Македонски"),
        new("mg", "Malagasy", "Malagasy"),
        new("ms", "Malay", "Bahasa Melayu"),
        new("ml", "Malayalam", "മലയാളം"),
        new("mt", "Maltese", "Malti"),
        new("mi", "Maori", "Te Reo Māori"),
        new("mr", "Marathi", "मराठी"),
        new("mn", "Mongolian", "Монгол"),
        new("ne", "Nepali", "नेपाली"),
        new("no", "Norwegian", "Norsk"),
        new("nn", "Nynorsk", "Norsk nynorsk"),
        new("oc", "Occitan", "Occitan"),
        new("ps", "Pashto", "پښتو"),
        new("fa", "Persian", "فارسی"),
        new("pl", "Polish", "Polski"),
        new("pt", "Portuguese", "Português"),
        new("pa", "Punjabi", "ਪੰਜਾਬੀ"),
        new("ro", "Romanian", "Română"),
        new("ru", "Russian", "Русский"),
        new("sa", "Sanskrit", "संस्कृतम्"),
        new("sr", "Serbian", "Српски"),
        new("sn", "Shona", "chiShona"),
        new("sd", "Sindhi", "سنڌي"),
        new("si", "Sinhala", "සිංහල"),
        new("sk", "Slovak", "Slovenčina"),
        new("sl", "Slovenian", "Slovenščina"),
        new("so", "Somali", "Soomaali"),
        new("es", "Spanish", "Español"),
        new("su", "Sundanese", "Basa Sunda"),
        new("sw", "Swahili", "Kiswahili"),
        new("sv", "Swedish", "Svenska"),
        new("tl", "Tagalog", "Filipino"),
        new("tg", "Tajik", "Тоҷикӣ"),
        new("ta", "Tamil", "தமிழ்"),
        new("tt", "Tatar", "Татар"),
        new("te", "Telugu", "తెలుగు"),
        new("th", "Thai", "ไทย"),
        new("bo", "Tibetan", "བོད་སྐད་"),
        new("tr", "Turkish", "Türkçe"),
        new("tk", "Turkmen", "Türkmençe"),
        new("uk", "Ukrainian", "Українська"),
        new("ur", "Urdu", "اردو"),
        new("uz", "Uzbek", "Oʻzbekcha"),
        new("vi", "Vietnamese", "Tiếng Việt"),
        new("cy", "Welsh", "Cymraeg"),
        new("yi", "Yiddish", "ייִדיש"),
        new("yo", "Yoruba", "Èdè Yorùbá")
    ];
}
